### ISSUE TITLE
Redirect Site Base Url Doesn't Respect @web alias in craft.

### ISSUE THREAD

**Issue by developingchris** [nystudio107/craft-retour#331]
### Describe the bug
Our craft instance is running behind a reverse proxy on an internal domain to our hosting provider. Servd.
But our web application reverse proxies at a different url.(e.g   project.production.servd.dev, is proxied to ourproject.com)
Setting the alias and environment variable has been fine for most functions of craft. 
However retour redirection is using the internal hostname and not the resulting url in the @web alias.

### To reproduce
Steps to reproduce the behaviour:
1. Have a site running on a subdomain, with the web alias running on another subdomain
2. When you curl the page the 302 you are returned will return the unaliased base url.

### Expected behaviour
The base url would ultimately read and respect the @web alias placed in the config for the given site as the ultimately base url.

### Versions
- Plugin version: 5.0.6
- Craft version: 5.5.10

**Comment by khalwat** [comment]
Retour should be reading this setting from the URL set in Settings -> Sites in your Craft setup. Can you verify for me what those are set to in this case with a screenshot or such?

**Comment by khalwat** [comment]
@developingchris ?

**Comment by developingchris** [comment]
Thank you for getting back to me, I've had to send a request in, because our setup seems to be different than what you are describing. the closest thing I can find is that in the repo that is built prior to deploy there is a yaml file called 
`config/sites/default-<hash>.yaml`
It contains this:
```YAML
baseUrl: $PRIMARY_SITE_URL
handle: default
hasUrls: true
language: en-US
name: $CRAFT_SYSTEM_NAME
primary: true
siteGroup: 75a227e5-cd7e-4ffe-9bde-18154f5f5be6 # $CRAFT_SYSTEM_NAME
sortOrder: 1
```
and the env var in the container for that is set to the url I desire to be used by retour.
